import { Shield, Globe, Award, Info } from 'lucide-react';

interface PrintFooterProps {
  currentPath?: string;
}

/**
 * Dedicated Printer-Friendly Footer Component
 * Hidden on-screen (hidden print:block) and formatted cleanly for physical paper prints and PDF exports.
 * Includes legal disclaimers, affiliate disclosure, author metadata, and verification details.
 */
export default function PrintFooter({ currentPath = '' }: PrintFooterProps) {
  const printDate = new Date().toLocaleDateString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });

  const fullUrl = `https://crmsolo.online${currentPath}`;

  return (
    <footer className="hidden print:block mt-8 pt-6 border-t-2 border-primary text-primary font-sans text-[9pt] leading-tight">
      <div className="space-y-4">
        {/* Top Header Row */}
        <div className="flex justify-between items-start border-b border-gray-300 pb-3">
          <div>
            <div className="flex items-center gap-1.5 font-display font-black text-[12pt] uppercase tracking-tight text-primary">
              <span>🏆 CRMSOLO</span>
              <span className="text-[7pt] font-mono font-bold bg-primary text-white px-1.5 py-0.5 rounded-xs">
                INDEPENDENT EVALUATION REPORT
              </span>
            </div>
            <p className="text-[8pt] text-gray-600 font-mono mt-0.5">
              The Independent CRM &amp; Software Intelligence Hub for Solo Real Estate Practitioners
            </p>
          </div>
          <div className="text-right text-[8pt] font-mono text-gray-600 space-y-0.5">
            <p className="font-bold text-primary flex items-center justify-end gap-1">
              <Shield className="w-3 h-3 text-success inline" /> Verified Independent Report
            </p>
            <p>Printed: {printDate}</p>
            <p className="truncate max-w-[280px]">URL: {fullUrl}</p>
          </div>
        </div>

        {/* Methodology & Author Credit */}
        <div className="grid grid-cols-2 gap-4 text-[8.5pt] bg-gray-50 p-3 rounded-md border border-gray-200">
          <div>
            <span className="font-bold text-primary uppercase text-[7.5pt] tracking-wider block font-mono flex items-center gap-1">
              <Award className="w-3 h-3 text-primary inline" /> Research &amp; Testing Methodology
            </span>
            <p className="text-gray-700 mt-1">
              Evaluated using CRMsolo's E-E-A-T framework across 14 solo real estate workflows, including speed-to-lead routing, Gmail/Outlook two-way sync, and mobile deal management.
            </p>
          </div>
          <div>
            <span className="font-bold text-primary uppercase text-[7.5pt] tracking-wider block font-mono flex items-center gap-1">
              <Info className="w-3 h-3 text-primary inline" /> Author &amp; Contact Metadata
            </span>
            <p className="text-gray-700 mt-1">
              Lead Evaluator: Eugene Boniface • Avenida de Esteiro 161 Ferrol, Spain • Contact: Eugeneboniface4@yahoo.com
            </p>
          </div>
        </div>

        {/* Standard Legal Disclaimers & Affiliate Disclosures */}
        <div className="space-y-1.5 text-[7.5pt] text-gray-600 leading-normal border-t border-gray-200 pt-3">
          <p>
            <strong>Legal Disclaimer:</strong> Ratings, ROI projections, and software recommendations generated by CRMsolo are calculated using standardized real estate industry benchmarks and user-provided inputs. Individual agent performance, regional commission split structures, local MLS rules, and lead conversion rates will vary. This document is provided for informational and educational purposes only.
          </p>
          <p>
            <strong>Affiliate Disclosure:</strong> CRMsolo maintains strict editorial independence. We may receive affiliate compensation when users click links or register for trials with software vendors reviewed on our site. Referral fees never influence our numerical rating criteria or editorial verdicts.
          </p>
        </div>

        {/* Copyright & Verification URL Footer */}
        <div className="flex justify-between items-center text-[8pt] font-mono text-gray-500 pt-2 border-t border-gray-300">
          <div>
            &copy; {new Date().getFullYear()} CRMsolo (crmsolo.online). All rights reserved.
          </div>
          <div className="flex items-center gap-1 font-bold text-primary">
            <Globe className="w-3 h-3 text-primary" /> crmsolo.online
          </div>
        </div>
      </div>
    </footer>
  );
}
